config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  get 'pages/home'
  get 'pages/user'
  get 'pages/admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/pages/admin.html.erb
<h1>Pages#admin</h1>
<p>Find me in app/views/pages/admin.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome to Home Page</h1>

<% if user_signed_in? %>
    <h1>User Sign In</h1>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
    <%= link_to "Edit User", edit_user_registration_path %>
<% elsif !admin_signed_in? %>
    <h1>User</h1>
    <%= link_to "Sign Up", new_user_registration_path %>
    <%= link_to "Sign In", new_user_session_path %>
<% end %>

<% if admin_signed_in? %>
    <h1>Admin Signed In</h1>
    <%= link_to "Sign Out", destroy_admin_session_path, method: :delete, data: { turbo_method: :delete } %>
    <%= link_to "Edit User", edit_admin_registration_path %>
<% elsif !user_signed_in? %>
    <h1>Admin</h1>
    <%= link_to "Sign Up", new_admin_registration_path %>
    <%= link_to "Sign In", new_admin_session_path %>
<% end %>

<h1>Pages</h1>
<%= link_to "Home", root_path %>
<%= link_to "Users", pages_user_path %>
<%= link_to "Admins", pages_admin_path %>

app/views/pages/user.html.erb
<h1>Pages#user</h1>
<p>Find me in app/views/pages/user.html.erb</p>